/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class watermark_wmLib */

#ifndef _Included_watermark_wmLib
#define _Included_watermark_wmLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     watermark_wmLib
 * Method:    addwm
 * Signature: ([B[BIII)I
 */
JNIEXPORT jint JNICALL Java_watermark_wmLib_addwm
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     watermark_wmLib
 * Method:    detwm
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_watermark_wmLib_detwm
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
